title: "EDH 7916: Contemporary Research in Higher Education"
course: edh7916
baseurl: "/{{ site.course }}"
description: PhD course in quantitative research workflow
repo: https://github.com/btskinner/{{ site.course }}
zip: https://github.com/btskinner/{{ site.course }}/zipball/{{ site.course }}

scripts: scripts
data: data

info:
  term: Spring 2020 
  location: University of Florida
  building: Norman Hall
  room: NRN 1-239

contact:
  name: Benjamin Skinner
  title: Assistant Professor of Higher Education and Policy
  school: University of Florida
  github: 
    name: btskinner
    url: https://github.com/btskinner
  url: https://www.btskinner.io
  uva_url: https://education.ufl.edu/faculty/skinner-benjamin-t/
  email: btskinner@coe.ufl.edu
  twitter: https://twitter.com/btskinner

epw:
  url: https://education.ufl.edu/higher-education/
  logo: http://identity.ufl.edu/download/colleges/college_of_education/College-of-Education-UF.png

# misc opts

theme: jekyll-theme-minimal
syntax: default
mapstyle: light-v9
google_analytics: UA-63981025-1
mathjax: true

# files / directories to exclude when building
exclude: ["*.Rmd", _working]

# collection of modules
collections:
  modules:
    output: true
    permalink: /:collection/:path
