title: "EDH 7916: Contemporary Research in Higher Education"
course: edh7916
baseurl: ""
description: |
  A course in quantitative research workflow for PhD students in
  the higher education administration program at the University of Florida
repo: https://github.com/btskinner/edh7916
zip: https://github.com/btskinner/edh7916/zipball/edh7916

scripts: scripts
data: data

info:
  term: Spring 2020 
  location: University of Florida
  building: Norman Hall
  room: NRN 1-239
  office: NRNA 2-230F
  officehrs: "Tuesday (3p - 5p)"

contact:
  name: Benjamin Skinner
  title: Assistant Professor of Higher Education and Policy
  shorttitle: Assistant Professor
  school: University of Florida
  github: 
    name: btskinner
    url: https://github.com/btskinner
  url: https://www.btskinner.io
  uva_url: https://education.ufl.edu/faculty/skinner-benjamin-t/
  email: btskinner@coe.ufl.edu
  twitter: https://twitter.com/btskinner

ufl:
  url: https://education.ufl.edu/higher-education/
  logo: College-of-Education-UF.png

# misc opts

theme: jekyll-theme-minimal
syntax: default
mapstyle: light-v9
google_analytics: UA-63981025-1
mathjax: true
future: true

# files / directories to exclude when building
exclude: ["*.Rmd", _working, README.md, kbuild.sh, Gemfile, Gemfile.lock]

# collection of modules
collections:
  modules:
    output: true
    permalink: /:collection/:path
